export type Article = { slug: string; title: string; description: string; category: string; focus: string; checklist: string[] };

export const articles: Article[] = [
  ["beneficios-corporativos-por-onde-comecar","Benefícios corporativos: por onde começar uma revisão","Estruture uma revisão de benefícios a partir de dados, pessoas e rotina — antes de comparar fornecedores.","Estratégia","custo, utilização e experiência dos colaboradores",["Mapear quem usa e quem não usa cada benefício","Separar custo contratado de custo realmente percebido","Definir uma prioridade por vez"]],
  ["sinistralidade-plano-saude-empresa","Sinistralidade do plano de saúde: o que acompanhar","Entenda quais perguntas ajudam RH e financeiro a ler a sinistralidade sem decisões precipitadas.","Saúde corporativa","histórico, perfil de utilização e renovação",["Comparar períodos equivalentes","Verificar concentração de eventos","Pedir contexto antes de propor mudança"]],
  ["reajuste-plano-saude-empresarial","Reajuste do plano empresarial: como se preparar","A renovação deve começar antes da proposta chegar. Veja um roteiro objetivo para a conversa.","Saúde corporativa","antecedência, dados e cenários",["Organizar contrato e faturas","Conferir rede e utilização","Definir limites de orçamento e serviço"]],
  ["beneficio-flexivel-ou-va-vr","Benefício flexível ou VA/VR: como decidir","A escolha não é sobre moda. É sobre aderência, governança e entendimento do time.","Cartões e vales","perfil do público e política interna",["Ouvir grupos representativos","Validar regras de uso e aceitação","Planejar comunicação antes da troca"]],
  ["politica-de-beneficios-clara","Como criar uma política de benefícios clara","Uma política simples reduz dúvidas repetidas, exceções informais e dependência do RH.","Governança","critérios, elegibilidade e comunicação",["Documentar quem é elegível","Explicar inclusões e desligamentos","Manter um canal de dúvidas atualizado"]],
  ["reduzir-chamados-rh-beneficios","Como reduzir chamados ao RH sobre benefícios","Grande parte das dúvidas nasce de linguagem confusa e onboarding incompleto.","Experiência do colaborador","comunicação ao longo da jornada",["Criar perguntas frequentes por benefício","Reforçar orientações em marcos da jornada","Medir os assuntos mais recorrentes"]],
  ["auditoria-beneficios-corporativos","Auditoria de benefícios: o que revisar primeiro","Uma auditoria útil prioriza riscos e oportunidades práticas, sem transformar tudo em planilha.","Auditoria","contratos, custos e operação",["Listar contratos e vencimentos","Checar regras que viraram exceção","Relacionar custos a objetivos de pessoas"]],
  ["indicadores-rh-beneficios","Indicadores de benefícios que ajudam o RH a decidir","Poucos indicadores bem escolhidos são melhores que um painel impossível de acompanhar.","Dados","uso, custo e percepção",["Acompanhar adesão por benefício","Monitorar custo por pessoa","Cruzar dados com dúvidas e reclamações"]],
  ["onboarding-beneficios-colaboradores","Onboarding de benefícios: como evitar confusão no início","A experiência começa no primeiro dia. Um roteiro claro diminui retrabalho e frustração.","Experiência do colaborador","acesso, prazos e canais",["Explicar o que entra em vigor e quando","Centralizar links e documentos","Indicar onde pedir ajuda"]],
  ["troca-de-fornecedor-beneficios","Troca de fornecedor de benefícios sem ruído","A implantação precisa ser conduzida como mudança de rotina, não apenas como contratação.","Implantação","transição, dados e comunicação",["Definir responsáveis por cada etapa","Validar dados antes da virada","Preparar comunicação com antecedência"]],
  ["rede-credenciada-plano-saude","Rede credenciada: como avaliar além da lista","A lista de nomes é apenas o começo. O importante é entender o uso real de cada público.","Saúde corporativa","localização, especialidades e rotina",["Mapear onde o time mora e trabalha","Checar hospitais e laboratórios relevantes","Explicar limites com clareza"]],
  ["coparticipacao-plano-saude","Coparticipação: quando exige mais cuidado","O modelo pode mudar comportamento e percepção. A decisão precisa considerar comunicação e previsibilidade.","Saúde corporativa","regras, orçamento e percepção",["Simular cenários comuns","Revisar a linguagem da política","Planejar suporte para dúvidas"]],
  ["beneficios-para-empresas-em-crescimento","Benefícios em empresas em crescimento: o que muda","Quando a empresa cresce, a solução que funcionava no início pode perder clareza e controle.","Estratégia","escala, processos e consistência",["Revisar elegibilidade","Padronizar cadastros","Reavaliar o atendimento ao colaborador"]],
  ["lgpd-gestao-de-beneficios","LGPD na gestão de benefícios: cuidados práticos","Dados pessoais devem ser pedidos apenas quando necessários e tratados com processo claro.","Governança","minimização, acesso e transparência",["Definir quem acessa cada dado","Evitar planilhas com informação sensível","Informar finalidade e canais de suporte"]],
  ["comunicacao-beneficios-mudanca","Como comunicar mudanças de benefícios","Antecipação, contexto e mensagens simples reduzem resistência e mensagens para o RH.","Comunicação","timing, clareza e próximos passos",["Explicar o que muda e o que não muda","Enviar cronograma objetivo","Abrir canal para dúvidas reais"]],
  ["beneficios-e-retencao","Benefícios e retenção: como sair do achismo","Benefícios influenciam a experiência, mas precisam estar conectados ao que as pessoas valorizam.","Pessoas","escuta, consistência e jornada",["Usar pesquisas internas com contexto","Comparar percepção entre públicos","Transformar achados em prioridades"]],
  ["custo-invisivel-beneficios","O custo invisível de uma operação de benefícios confusa","Retrabalho, exceções e dúvidas recorrentes também consomem orçamento — mesmo fora da fatura.","Operação","tempo do RH e experiência",["Estimar horas gastas com retrabalho","Identificar etapas manuais","Criar padrões para exceções"]],
  ["checklist-renovacao-beneficios","Checklist de renovação de benefícios corporativos","Use este roteiro para chegar à renovação com dados e menos urgência.","Processo","preparo e decisão",["Reunir dados e contratos","Mapear pontos de atrito","Definir decisão, responsável e prazo"]],
  ["diagnostico-beneficios-sem-fornecedor","Por que diagnosticar antes de escolher fornecedor","Antes de comparar propostas, vale entender o problema que a empresa realmente quer resolver.","Método","cenário e critérios",["Descrever a dor sem citar marca","Organizar critérios de escolha","Registrar hipóteses para validar"]],
  ["governanca-beneficios-cfo-rh","RH e financeiro: como decidir benefícios juntos","A decisão melhora quando experiência e sustentabilidade financeira entram na mesma conversa.","Governança","responsabilidades e acordos",["Combinar indicadores comuns","Definir quem aprova cada etapa","Registrar decisões e aprendizados"]],
].map(([slug,title,description,category,focus,checklist]) => ({ slug, title, description, category, focus, checklist }));

export const articleBySlug = (slug: string) => articles.find((article) => article.slug === slug);
