import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteFooter } from "../../components/SiteFooter";
import { SiteHeader } from "../../components/SiteHeader";
import { articleBySlug, articles } from "../../lib/article-data";

export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const article = articleBySlug((await params).slug); if (!article) return {}; return { title: article.title, description: article.description, alternates: { canonical: `https://www.gestaobeneficios.com.br/artigos/${article.slug}` } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const article = articleBySlug((await params).slug); if (!article) notFound(); return <main><SiteHeader /><article className="editorial-article"><header><p className="eyebrow"><span /> {article.category}</p><p className="article-breadcrumb"><a href="/artigos">Biblioteca</a> / {article.category}</p><h1>{article.title}</h1><p className="article-intro">{article.description}</p></header><section><h2>O que vale observar</h2><p>Quando o tema é {article.focus}, comparar apenas preço ou uma lista de opções costuma deixar pontos importantes de fora. Uma decisão bem conduzida começa ao colocar o cenário da empresa e das pessoas no centro da conversa.</p><p>O objetivo não é encontrar uma resposta automática, e sim definir critérios claros, reunir informação suficiente e transformar a próxima ação em algo compreensível para RH, financeiro e colaboradores.</p></section><section><h2>Checklist prático</h2><ul>{article.checklist.map(item => <li key={item}>{item}</li>)}</ul></section><section><h2>Como avançar sem improviso</h2><p>Registre o que já funciona, os pontos de atrito e o que precisa ser validado. Em seguida, escolha uma prioridade e acompanhe o efeito dela antes de abrir várias frentes ao mesmo tempo.</p><p>Se o cenário ainda estiver confuso, o diagnóstico inicial ajuda a organizar perguntas antes de decidir qualquer fornecedor ou modelo.</p><a className="button" href="/diagnostico">Fazer diagnóstico gratuito</a></section></article><SiteFooter /></main>; }
